"""empty message

Revision ID: 1b7d8838eba0
Revises: f0253ef1c017
Create Date: 2023-07-27 21:18:30.707695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b7d8838eba0'
down_revision = 'f0253ef1c017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('date_time', sa.String(length=64), nullable=True))
        batch_op.drop_column('date')
        batch_op.drop_column('time')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('time', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.drop_column('date_time')
        batch_op.drop_column('reference')

    # ### end Alembic commands ###
