"""empty message

Revision ID: 39368d989cb0
Revises: 71fc7071ac91
Create Date: 2023-07-27 23:02:09.378953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39368d989cb0'
down_revision = '71fc7071ac91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('date_time',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('date_time',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###
