"""empty message

Revision ID: 635fb5405f00
Revises: 1b7d8838eba0
Create Date: 2023-07-27 21:35:06.182438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635fb5405f00'
down_revision = '1b7d8838eba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
